export const initialSession = {
  id: null,
  name: "Untitled Session",
  bpm: 120,
  key: "C",
  scale: "minor",
  timeSignature: [4, 4],
  tracks: [],
  playheadPosition: 0,
  loopStart: 0,
  loopEnd: 8,
  loopEnabled: false,
  isPlaying: false,
  selectedTrackId: null,
  selectedClipId: null,
  openPanel: "mixer",
  aiSuggestions: [],
  aiMessages: [],
  aiChatHistory: [],
  aiCurrentChatId: null,
};
